In [6]:
from collections import namedtuple
from gensim.models import doc2vec
from konlpy.tag import Twitter
import multiprocessing
from gensim.models import Doc2Vec
import numpy as np
import pandas as pd

# 다항분포 나이브베이즈를 위한 라이브러리를 임포트합니다
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# 모델의 정확도 평가를 위해 임포트합니다
from sklearn.metrics import accuracy_score
from konlpy.tag import Kkma
from konlpy.utils import pprint
from sklearn.model_selection import train_test_split 
# Gaussian Naive Bayes로 iris 데이터를 분류하도록 하겠습니다 
from sklearn.naive_bayes import GaussianNB 
# 분류 성능을 측정하기 위해 metrics와 accuracy_score를 임포트합니다 
from sklearn import metrics 
from sklearn.metrics import accuracy_score

twitter = Twitter()
def read_data(filename):
    with open(filename, 'r',encoding='utf-8') as f:
        data = [line.split('\t') for line in f.read().splitlines()]
    return data

def tokenize(doc):
# norm, stem은 optional
    return ['/'.join(t) for t in twitter.pos(doc, norm=True, stem=True)]

data = pd.read_csv('test.csv',encoding='euc-kr')


# load train data
doc_vectorizer = Doc2Vec.load('model_jh/리뷰모음_train_랄라.model')
# doc2vec 에서 필요한 데이터 형식으로 변경
df_x = [doc_vectorizer.infer_vector(tokenize(d)) for d in data['글'].tolist()]
# 분류를 위한 피쳐 생성
df_y = data['tag'].values

X_train,X_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.5)
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

# 테스트 socre 확인
print("Number of right labeled points out of a total %d points : %.2f %%"
      % (len(X_test),100*(len(X_test)-(y_test != y_pred).sum())/len(X_test)))
accuracy_score(y_test, y_pred)


Number of right labeled points out of a total 2 points : 50.00 %


0.5

In [1]:
from Preprocessor import Preprocessor

#FilterReview
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn import metrics 
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
'''
readCSV :CSV 파일을 읽는다. 고정포맷이 정해짐 
trainModel(ts =0.25): 입력된 모델에서 학습시킨다. ts 테스트 케이스 
predict(): 학습시킨 모델에 test데이터가 입력되면 예측한다. 
writePredictionResult(): 예측 결과를 파일로 출력한다. 
'''
class FilterReviewSV:
    def __init__(self):
        pass
    def input_X(self, para):
        pre = Preprocessor()
        pre.setPara(para)
        self.X = pre.transVector()
    def input_Y(self, result):
        self.Y = result
        
    def readCSV(self,filename,tag=True):
        self.data = pd.read_csv(filename,encoding='euc-kr')
        self.X_content = self.data['글'].values
        self.input_X(self.X_content)
        if tag == True:
            self.input_Y(self.data['tag'].values)
        
    def trainModel(self,ts):
        self.X_train,self.X_test,self.y_train,self.y_test=train_test_split(self.X,self.Y,test_size=ts)
        self.gnb = GaussianNB()
        self.y_pred = self.gnb.fit(self.X_train, self.y_train).predict(self.X_test)

        # 테스트 socre 확인
        print("Number of right labeled points out of a total %d points : %.2f %%"
      % (len(self.X),100*(len(self.X)-(self.y_test != self.y_pred).sum())/len(self.X)))
    def predict(self):
        self.y_pred = self.gnb.predict(self.X)
        self.df = pd.DataFrame({'p_tag':self.y_pred, '글':self.X_content})
        return self.y_pred
    def writePredictionResult(self, filename):
        self.df.to_csv(filename,encoding='euc-kr')
        
fr = FilterReview()
#fr.input_X('나는 멍청이다.\n취업 좀 하자\n취업 좀 하자\n취업 좀 하자')
#fr.input_Y([1,0,1,0])
fr.readCSV(tag=True,filename='Train.csv')
fr.trainModel(ts=0.25)

fr.readCSV(tag=False,filename='Test.csv')
fr.predict()

fr.writePredictionResult('sample.csv')
print(fr.y_pred)
fr.X_content


C:\Users\JH\Anaconda3\envs\farm\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\JH\Anaconda3\envs\farm\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


['나는 멍청하다.' '지수는 왜 나갔을까?' '언제 취업하지…' '잠온다.']
Number of right labeled points out of a total 4 points : 75.00 %
['나는 멍청하다.' '지수는 왜 나갔을까?' '언제 취업하지…' '잠온다.']
[1 1 1 0]


array(['나는 멍청하다.', '지수는 왜 나갔을까?', '언제 취업하지…', '잠온다.'], dtype=object)

In [70]:
import numpy as np
import pandas as pd

# 다항분포 나이브베이즈를 위한 라이브러리를 임포트합니다
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# 모델의 정확도 평가를 위해 임포트합니다
from sklearn.metrics import accuracy_score

In [71]:
data = pd.read_csv('test.csv',encoding='euc-kr')
data.values.tolist()
data

글    조회수  tag
0     나는 멍청하다.  10000    1
1  지수는 왜 나갔을까?    200    0
2     언제 취업하지…    300    1
3         잠온다.      2    0

In [72]:
def tokenize(doc):
# norm, stem은 optional
    return ['/'.join(t) for t in twitter.pos(doc, norm=True, stem=True)]

In [73]:
from konlpy.tag import Kkma
from konlpy.utils import pprint

# load train data
doc_vectorizer = Doc2Vec.load('model_jh/리뷰모음_train_랄라.model')
# doc2vec 에서 필요한 데이터 형식으로 변경
TaggedDocument = namedtuple('TaggedDocument', 'words tags')

In [74]:
df_x = [doc_vectorizer.infer_vector(tokenize(d)) for d in data['글'].tolist()]
df_x 
#[tokenize(d) for d in data['글'].tolist()]

[array([ 4.36840989e-02, -7.04494938e-02, -2.39002286e-04,  1.24077864e-01,
         9.14426148e-02,  4.02692445e-02,  2.94342805e-02, -7.53648132e-02,
         5.66745065e-02,  1.05614759e-01,  8.85230675e-02,  2.52115905e-01,
         1.53827354e-01, -1.37313753e-01,  1.10528618e-01, -2.86951333e-01,
         6.82718828e-02,  3.48693994e-03,  8.80889967e-02, -6.51722401e-02,
         1.05374545e-01, -3.27066481e-02, -1.03931777e-01,  5.50160781e-02,
         3.13474517e-03,  2.32628092e-01, -1.08727947e-01,  2.98645906e-02,
         1.15790684e-02,  2.94343904e-02, -6.29565641e-02,  4.84019183e-02,
         8.83577093e-02, -1.02702782e-01, -1.53425336e-01, -6.83640093e-02,
        -5.38449828e-03,  9.71658602e-02, -8.28554034e-02, -5.71908318e-02,
        -4.91139591e-02,  4.65504564e-02,  1.07143156e-01, -7.27701783e-02,
        -1.13491222e-01,  1.88210290e-02,  2.33601592e-02,  7.40942657e-02,
         1.46534860e-01, -3.85597572e-02, -1.77085564e-01,  3.18102203e-02,
        -3.5

In [75]:
'''
train_docs = [(tokenize(row[0]), row[2]) for row in data.values.tolist()]

# doc2vec 에서 필요한 데이터 형식으로 변경
TaggedDocument = namedtuple('TaggedDocument', 'words tags')
tagged_train_docs = [TaggedDocument(d, [c]) for d, c in train_docs]
train_x = [doc_vectorizer.infer_vector(doc.words) for doc in tagged_train_docs]
train_x
#[TaggedDocument(d, [c]) for d, c in train_docs]
'''

"\ntrain_docs = [(tokenize(row[0]), row[2]) for row in data.values.tolist()]\n\n# doc2vec 에서 필요한 데이터 형식으로 변경\nTaggedDocument = namedtuple('TaggedDocument', 'words tags')\ntagged_train_docs = [TaggedDocument(d, [c]) for d, c in train_docs]\ntrain_x = [doc_vectorizer.infer_vector(doc.words) for doc in tagged_train_docs]\ntrain_x\n#[TaggedDocument(d, [c]) for d, c in train_docs]\n"

In [76]:
# 분류를 위한 피쳐 생성
df_y = data['tag'].values


In [77]:
df_x

[array([ 4.36840989e-02, -7.04494938e-02, -2.39002286e-04,  1.24077864e-01,
         9.14426148e-02,  4.02692445e-02,  2.94342805e-02, -7.53648132e-02,
         5.66745065e-02,  1.05614759e-01,  8.85230675e-02,  2.52115905e-01,
         1.53827354e-01, -1.37313753e-01,  1.10528618e-01, -2.86951333e-01,
         6.82718828e-02,  3.48693994e-03,  8.80889967e-02, -6.51722401e-02,
         1.05374545e-01, -3.27066481e-02, -1.03931777e-01,  5.50160781e-02,
         3.13474517e-03,  2.32628092e-01, -1.08727947e-01,  2.98645906e-02,
         1.15790684e-02,  2.94343904e-02, -6.29565641e-02,  4.84019183e-02,
         8.83577093e-02, -1.02702782e-01, -1.53425336e-01, -6.83640093e-02,
        -5.38449828e-03,  9.71658602e-02, -8.28554034e-02, -5.71908318e-02,
        -4.91139591e-02,  4.65504564e-02,  1.07143156e-01, -7.27701783e-02,
        -1.13491222e-01,  1.88210290e-02,  2.33601592e-02,  7.40942657e-02,
         1.46534860e-01, -3.85597572e-02, -1.77085564e-01,  3.18102203e-02,
        -3.5

In [79]:
df_y

array([1, 0, 1, 0], dtype=int64)

In [80]:
from sklearn.model_selection import train_test_split 
# Gaussian Naive Bayes로 iris 데이터를 분류하도록 하겠습니다 
from sklearn.naive_bayes import GaussianNB 
# 분류 성능을 측정하기 위해 metrics와 accuracy_score를 임포트합니다 
from sklearn import metrics 
from sklearn.metrics import accuracy_score


In [145]:
df_x[0].shape

(300,)

In [146]:
X_train,X_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.5)


In [85]:
df_y.shape
type(df_x)

list

In [53]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

# 테스트 socre 확인
print("Number of right labeled points out of a total %d points : %.2f %%"
      % (len(train_x),100*(len(train_x)-(y_test != y_pred).sum())/len(train_x)))


Number of right labeled points out of a total 4 points : 75.00 %


In [54]:
accuracy_score(y_test, y_pred)

0.5

In [55]:
y_test

array([1, 0], dtype=int64)

In [56]:
y_pred

array([1, 1], dtype=int64)